@baseURL = http://localhost:8000/api
@jwt = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Mn0.EVGC36tvMWZqq24TdpAqBqbSWBHcUzqGWeYy5jO10MU

################# USUARIO ####################


###
POST {{baseURL}}/usuarios
Content-Type: application/json

{
    "usuario": {
        "nome": "Carlos",
        "email": "carlos@teste.com",
        "senha": "123456"
    }
}

###
POST {{baseURL}}/login
Content-Type: application/json

{
    "email": "carlos@teste.com",
    "senha": "123456"
}

################ TAREFAS ######################

### Cadastrar
POST {{baseURL}}/tarefas
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "tarefa": {
        "descricao": "Teste",
        "data": "2021-04-22"
    }
}

### Buscar
GET {{baseURL}}/tarefas
Authorization: Bearer {{jwt}}
Content-Type: application/json


### ATUALIZAR
@tarefaID = 1
PUT {{baseURL}}/tarefas/{{tarefaID}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "tarefa": {
        "descricao": "Teste 1",
        "data": "2021-05-22"
    }
}


### DELETAR
DELETE {{baseURL}}/tarefas/{{tarefaID}}
Authorization: Bearer {{jwt}}
